Azdevify contoso-chat
jongio/contoso-chat pull request #1
Opened 2024-03-04 09:36 UTC by zedy-wj

Main features:

1. Provisioning via `azd`. (Complete)
2. Add hooks to complete connections. (Doing)
3. Deploying via `azd`. (Not clear, waiting for reply)

2024-03-04 20:20 UTC, jongio requested changes

2024-03-04 20:20 UTC, jongio commented on azure.yaml
> +  template: contoso-chat@0.0.1-beta
Please keep the workflow

2024-03-04 20:20 UTC, jongio commented on azure.yaml
> +    run: ./infra/hooks/prepenv.sh
Let's keep the postprovision file name and you don't need to start with ./

2024-03-04 20:20 UTC, jongio commented on connections/create-connections.py
> +import os
See my postprovision.sh file to see how I'm doing this with jypter - We don't want to have the code duplicated in the repo.

2024-03-04 20:20 UTC, jongio commented on infra/app/ml.bicep
> +param contosoChatSfAIName string = 'contoso-chat-sf-ai'
```suggestion
param contosoChatSfAiName string = 'contoso-chat-sf-ai'
```

2024-03-04 20:20 UTC, jongio commented on infra/app/ml.bicep
> +resource mlHub 'Microsoft.MachineLearningServices/workspaces@2023-08-01-preview' = {
```suggestion
resource workspace 'Microsoft.MachineLearningServices/workspaces@2023-08-01-preview' = {
```

2024-03-04 20:20 UTC, jongio commented on infra/app/ml.bicep
> +    discoveryUrl: 'https://swedencentral.api.azureml.ms/discovery'
Seems like this should be the location of the resource, not hardcoded to swedencentral

2024-03-04 20:20 UTC, jongio commented on infra/app/ml.bicep
> +resource mlProject 'Microsoft.MachineLearningServices/workspaces@2023-10-01' = {
```suggestion
resource project 'Microsoft.MachineLearningServices/workspaces@2023-10-01' = {
```

2024-03-04 20:20 UTC, jongio commented on infra/app/ml.bicep
> +    friendlyName: contosoChatSfAIName
```suggestion
    friendlyName: contosoChatSfAiName
```

2024-03-04 20:20 UTC, jongio commented on infra/app/ml.bicep
> +  name: openAIName
Keep consistent Ai instead of AI, check all files please.

2024-03-04 20:20 UTC, jongio commented on infra/core/database/cosmos/sql/cosmos-sql-db.bicep
> +metadata description = 'Creates an Azure Cosmos DB for NoSQL account with a database.'
did you have to make any changes from azd/infra/core for this project?

2024-03-04 20:20 UTC, jongio commented on infra/hooks/prepenv.sh
> +echo "Loading azd .env file from current environment"
Please diff with my postprovision.sh script

2024-03-04 20:20 UTC, jongio commented on infra/main.bicep
> +param azureOpenAIResourceName string = ''
```suggestion
param azureOpenAiResourceName string = ''
```

2024-03-04 20:20 UTC, jongio commented on infra/main.bicep
> +param workspacesApwsContosoChatSfAi362802272292Name string = 'apws-contosochatsfai362802272292'
Let's update this name to be something shorter.  Not sure why it was that long in the first plac.e

2024-03-05 02:35 UTC, zedy-wj commented on infra/core/database/cosmos/sql/cosmos-sql-db.bicep
> +metadata description = 'Creates an Azure Cosmos DB for NoSQL account with a database.'
Yes, we mainly modified the `container-registry` in core and configured [the creation of scopeMap](https://github.com/jongio/contoso-chat/pull/1/files#diff-82700b4bc57cc6f982085408349ebe12b24bcc0cdd7cc01bd2ce3d3a8da601f8R102-R105) resources for it, because we think this modification can be reused later.

As for other minor changes:
1. Added some default parameters in `container-registry`, such as `quarantinePolicy`, `trustPolicy`, etc. that were not available before.
2. Since some other resource IDs are needed when creating `MachineLearningServices`, these IDs are not output, so I added some required output IDs, such as [storageAccountId](https://github.com/jongio/contoso-chat/pull/1/files#diff-6c71e92c01838a849b8728b0368f0ac670f08310ccdd9df31fcab656f3567e19R88), [appInsightId](https://github.com/jongio/contoso-chat/pull/1/files#diff-e97bc2f50258546774b25a530dad18f715cf2fa070a9e91c474335114534d94cR31).

2024-03-05 09:08 UTC, zedy-wj commented
@jongio - Updated according to your comments. Please re-review it, thanks!

Regarding hooks, we used your original file(postprovision.sh) and modified some of the parameter names. And we added the steps to [install requirements](https://github.com/jongio/contoso-chat/pull/1/files#diff-b4dae3e1241bb856cb0942d1ffd5038172f42871ed7c12cd3931726cf71abb1aR77-R78).

2024-03-05 22:58 UTC, jongio requested changes

2024-03-05 22:58 UTC, jongio commented on azure.yaml
> +    interactive: false
Why false?

2024-03-05 22:58 UTC, jongio commented on infra/app/ml.bicep
> +param contosoChatSfAiprojName string = 'contoso-chat-sf-aiproj'
```suggestion
param contosoChatSfAiProjectName string = 'contoso-chat-sf-aiproj'
```

2024-03-05 22:58 UTC, jongio commented on infra/app/ml.bicep
> +param appInsightId string
```suggestion
param applicationInsightsId string
```

2024-03-05 22:58 UTC, jongio commented on infra/app/ml.bicep
> +    discoveryUrl: 'https://swedencentral.api.azureml.ms/discovery'
Let's use the location param for this.

2024-03-05 22:58 UTC, jongio commented on infra/app/ml.bicep
> +output workspace_principal_id string = workspace.identity.principalId
Note to check output casing

2024-03-05 22:58 UTC, jongio commented on infra/main.bicep
> +var openaiSubdomain = '${accountsContosoChatSfAiServicesName}${resourceToken}'
```suggestion
var openAiSubdomain = '${accountsContosoChatSfAiServicesName}${resourceToken}'
```

2024-03-05 22:58 UTC, jongio commented on infra/main.bicep
> +var openaiEndpoint = 'https://${openaiSubdomain}.openai.azure.com/'
```suggestion
var openAiEndpoint = 'https://${openaiSubdomain}.openai.azure.com/'
```

2024-03-05 22:58 UTC, jongio commented on infra/main.bicep
> +output AZURE_PROJECT_NAME string = machinelearning.outputs.project_name
Let's get consistent output casing.  I see camel and snake

2024-03-06 02:49 UTC, zedy-wj commented
@jongio - Updated according to your comments. Please re-review it, thanks!

2024-03-06 18:06 UTC, jongio requested changes

2024-03-06 18:06 UTC, jongio commented on infra/app/ml.bicep
> +  resource openaiConnection 'connections' = {
```suggestion
  resource openAiConnection 'connections' = {
```

2024-03-06 18:06 UTC, jongio commented on infra/app/ml.bicep
> +  resource openaiDefaultEndpoint 'endpoints' = {
```suggestion
  resource openAiDefaultEndpoint 'endpoints' = {
```

2024-03-06 18:06 UTC, jongio commented on infra/hooks/postprovision.sh
> +mlProjectName=$AZURE_PROJECT_NAME
```suggestion
mlProjectName=$AZURE_MLPROJECT_NAME
```

2024-03-06 18:06 UTC, jongio commented on infra/hooks/postprovision.sh
> +    echo "Ensure that AZURE_RESOURCE_GROUP, AZURE_SEARCH_NAME, AZURE_OPENAI_NAME, AZURE_COSMOS_NAME, AZURE_SUBSCRIPTION_ID, and AZURE_PROJECT_NAME are set."
```suggestion
    echo "Ensure that AZURE_RESOURCE_GROUP, AZURE_SEARCH_NAME, AZURE_OPENAI_NAME, AZURE_COSMOS_NAME, AZURE_SUBSCRIPTION_ID, and AZURE_MLPROJECT_NAME are set."
```

2024-03-06 18:06 UTC, jongio commented on infra/main.bicep
> +output AZURE_PROJECT_NAME string = machinelearning.outputs.projectName
```suggestion
output AZURE_MLPROJECT_NAME string = machineLearning.outputs.projectName
```

2024-03-06 18:06 UTC, jongio commented on infra/main.bicep
> +module machinelearning 'app/ml.bicep' = {
```suggestion
module machineLearning 'app/ml.bicep' = {
```

2024-03-06 18:06 UTC, jongio commented on infra/main.bicep
> +output AZURE_WORKSPACE_NAME string = machinelearning.outputs.workspaceName
```suggestion
output AZURE_WORKSPACE_NAME string = machineLearning.outputs.workspaceName
```

2024-03-06 18:06 UTC, jongio commented on infra/core/database/cosmos/sql/cosmos-sql-db.bicep
> +metadata description = 'Creates an Azure Cosmos DB for NoSQL account with a database.'
Can you please do a PR to azd/infra/core in azure-dev repo for anything that has changed?

2024-03-07 07:04 UTC, zedy-wj commented
> Can you please do a PR to azd/infra/core in azure-dev repo for anything that has changed?

@jongio - We have done a PR for anything changed in `infra/core`, please review it: https://github.com/Azure/azure-dev/pull/3495. In addition, your other comments have been processed, please re-review it, thanks!

2024-03-07 18:14 UTC, jongio approved these changes

2024-03-07 18:15 UTC, merged